{% set name = "wimsey" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wimsey-{{ version }}.tar.gz
  sha256: c292db500bcf1e48c3aced4052dd2530adb1dca2427fd99eb219cf489698674e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - narwhals >=1.10.0
    - fsspec >=2024.10.0

test:
  imports:
    - wimsey
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/benrutter/wimsey
  doc_url: https://benrutter.github.io/wimsey/
  summary: A lightweight data contracts framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
